# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d0370dde05197042e41c02226e79268ee11a084eff6af007ec3fec1e22c74991dc307140484294077c099f11ae7032af21fc1e5ef95c82b37cf484074e04400

test:
  secret_key_base: 913f832b64d1d89ea490fda88eb92296145f1e6cc438acb53e407970abaadc481ea3571d70f2f7b52445981142a9313fb9f8d6a93e9f3d2f686fd4a0a0ac6bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Settings.production[:secret] %>
